### ISSUE TITLE
Feature: add contributing docs to the issue agreement

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/.github#12]
### Type of feature

🍕 Feature

### Current behavior

When opening an issue we are tasked to read the contributing covenant, for the people that open issues in order to `.take` them, it is important to optionally add the contributing docs to the terms.

### Suggested solution

Add https://docs.opensauced.pizza/contributing/introduction-to-contributing/ next to the code of conduct link in all templates, make it optional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dhananjay-JSR** [comment]
can you explain a bit more to me ?? do I need to configure github action Triage bot in this repo or in this repo ( https://github.com/open-sauced/open-sauced )

**Comment by 0-vortex** [comment]
> can you explain a bit more to me ?? do I need to configure github action Triage bot in this repo or in this repo ( https://github.com/open-sauced/open-sauced )

Sure, it requires adding another checkbox at the very bottom of https://raw.githubusercontent.com/open-sauced/.github/main/.github/ISSUE_TEMPLATE/bug_report.yml and https://raw.githubusercontent.com/open-sauced/.github/main/.github/ISSUE_TEMPLATE/feature_request.yml
