### ISSUE TITLE
Feature: rename "opensauced.pizza" to "app.opensauced.pizza" in bug report template

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/.github#19]
### Type of feature

🐛 Fix

### Current behavior

![image](https://user-images.githubusercontent.com/52013393/194611982-13034924-4ee4-4ac7-8163-7e6a952bc78c.png)
Currently, the option "opensauced.pizza" refers to app.opensauced.pizza project but has an outdated name, since now all open sauced projects have "opensauced.pizza" in their names, but differ in the first section of it, like "hot" or "api". This is in bug report template.

### Suggested solution

So to be more clear on what we mean with "opensauced.pizza" and to be up to date with the new naming conventions, it should be updated to "app.opensauced.pizza".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sanmay321** [comment]
@Deadreyo hey I would like to work on this issue,

**Comment by Deadreyo** [comment]
> @Deadreyo hey I would like to work on this issue,

Feel free to! Assign it to yourself

**Comment by sanmay321** [comment]
@Deadreyo could u please assign me,

**Comment by 0-vortex** [comment]
> @Deadreyo could u please assign me,

Please read the guide: https://docs.opensauced.pizza/contributing/introduction-to-contributing/

**Comment by sanjaygupta972004** [comment]
.take.issue
