### ISSUE TITLE
Feature[DOCS]: Add Gitpod and CodeSpaces link to Contributing file 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/.github#44]
### Type of feature

🍕 Feature

### Current behavior

In my experience working with open source beginners, sometimes the directions to setting up a code environment do not always pan out, which creates a frustrating experience. Furthermore, some might not be able to afford their own computer and can only use virtual IDEs.

### Suggested solution

Adding links to [CodeSpaces](https://github.com/features/codespaces) and [Gitpod](https://www.gitpod.io/) to the [Contributing file](https://github.com/open-sauced/.github/blob/main/CONTRIBUTING.md) can make it easier for open source beginners to get started. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Can I work on the issue?

**Comment by CBID2** [comment]
> Can I work on the issue?

Go ahead @Lymah123
