### ISSUE TITLE
Change twitter icon X

### ISSUE THREAD

**Issue by Petsamuel** [open-sauced/.github#46]
### Describe the bug

Replacing The Twitter icon in the footer section to its new icon

### Steps to reproduce

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Closing this issue. This update was made
![Screenshot of the footer of OpenSauced’s website. The new logo for X(Twitter) is circled with blue.](https://github.com/open-sauced/.github/assets/105683440/bd55f9da-54a5-4bbd-9cb1-2a7e91ac8779)
