### ISSUE TITLE
Bug: Bug issue template is absence when creating an issue

### ISSUE THREAD

**Issue by adiati98** [open-sauced/.github#52]
### Type of feature

🐛 Fix

### Current behavior

Recently, there was an update to the `bug_report.yml` which caused an error and the absence of bug issue template as shown in the screenshots below.

**Note**: I'm using the feature issue template to submit this bug.

### YAML Syntax Error

![Screenshot 2024-03-24 041044](https://github.com/open-sauced/.github/assets/45172775/c843b825-ba44-4f6e-967f-6dd87916cc7a)

### Absence of bug issue template on app repo.

![Screenshot 2024-03-24 040740](https://github.com/open-sauced/.github/assets/45172775/2b83416f-fb87-49c6-82c8-9dab80aff270)

### Suggested solution

This bug is most likely caused by [incorrect indentantion](https://stackoverflow.com/a/54966747). Fixing the indentation may resolve this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
I would like to be assigned to the issue @open-sauced/triage @open-sauced/engineering.
Thank you!

**Comment by CBID2** [comment]
Go ahead @adiati98! :)
